name: build-and-test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test-all:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      
    defaults:
      run:
        working-directory: src
        
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x

    - name: Clean
      run: dotnet clean ./Mews.Fiscalization.SignatureChecker.sln --configuration Release && dotnet nuget locals all --clear
        
    - name: Install dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      run: dotnet test --no-restore --logger "trx;LogFileName=test-results-${{ runner.os }}.trx" || true

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Mews.Fiscalizations.SignatureChecker-${{ runner.os }} Tests
        path: "**/test-results-${{ runner.os }}.trx"
        reporter: dotnet-trx
        fail-on-error: true